name: Deploy at Two via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy_two:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Run git pull on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ssh-copilot-bot
            git fetch origin
            git pull
            sudo service ssh-copilot-bot restart
